### ISSUE TITLE
Not compatible with XDK cordova 5.1.1 iOS 

### ISSUE THREAD

**Issue by arjankuijpers** [cmackay/google-analytics-plugin#62] opened 2016-03-07 20:26 UTC
when trying to build with XDK 2866 
I get this error:

com.cmackay.plugins.googleanalytics/libGoogleAnalyticsServices.a(GAITrackerModel.o)
ld: 223 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cmackay** [comment] 2016-03-07 23:37
duplicate of #57 

I don't use the intel XDK so not sure why it doesn't work properly with cordova components. If you find out a fix, feel free to submit a PR.

**Comment by arjankuijpers** [comment] 2016-03-08 01:14
i found a version that works with the current XDK version: on android as iOS
commit: `[d94f91aa0ed18ebc829ec8d6c159c777edfa0744](https://github.com/cmackay/google-analytics-plugin/commit/d94f91aa0ed18ebc829ec8d6c159c777edfa0744)`

**Comment by cmackay** [comment] 2017-01-21 19:49
closing since I marked this as wont fix

**Closed by cmackay** 2017-01-21 19:49 UTC
Labels: wontfix
