### ISSUE TITLE
Xcode 7 BitCode linker error

### ISSUE THREAD

**Issue by dbroadhurst** [cmackay/google-analytics-plugin#48] opened 2015-09-18 04:46 UTC
I've run into the following linker error in Xcode 7.

com.cmackay.plugins.googleanalytics/libGoogleAnalyticsServices.a(TAGDataProvider.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by petarov** [comment] 2015-09-18 08:04
One of several issues cordova devs face now with iOS9 ;)

@cmackay ver [3.13](https://developers.google.com/analytics/devguides/collection/ios/v3/sdk-download) probably fixes this, although I don't have time to try it at the moment.

**Comment by cmackay** [comment] 2015-09-18 13:02
Thanks @dbroadhurst for reporting this. I will take a look at this in more detail this weekend and hopefully get a fix out soon. Thanks @petarov for the suggestion about v3.13. I will take a look at that and see if that resolves the issue.

**Comment by cmackay** [comment] 2015-09-18 22:01
I am not seeing this error. Xcode 7 is installed on my system but I don't build within xcode, I use the "cordova build ios" command. It builds successfully without any errors. Please provide more details on how I can reproduce this. Thanks!

**Comment by dbroadhurst** [comment] 2015-09-19 01:13
I think the problem happens when you build in Xcode 7 for a real device. Confirmed I can also build with cordova but you need to build in Xcode to release.

**Comment by cmackay** [comment] 2015-09-19 06:03
Thanks for the additional info. I tried building in xcode but my environment is not really setup currently for a release build. I don't have a developer certificate. I also tried the approach outlined in this http://stackoverflow.com/questions/24061063/how-can-i-deploy-create-ipa-iphone-app-using-cordova-build-ios-release

but I get the message:

No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

Maybe I can try getting the latest sdk updated and then you can verify if it resolves the issue you are having. I will let you know when I get it upgraded. Thanks!

**Comment by dbroadhurst** [comment] 2015-09-19 06:11
I tried the latest SDK but it didn't fix, although I just upgraded the lib so I could have missed a step. 

There's a lot of conversation around this being a known issue and people are just waiting for a google fix. It is possible to disable bitcode in the xcode build settings which seems to get through the build and link steps but I'm just not convinced analytics still works or how globally switching off bitcode affects other plugins that require bitcode. I'm going to keep searching and please let me know if there's anything I can do to help test any potential fixes.

**Comment by petarov** [comment] 2015-09-19 08:36
I also did a quick test and as @dbroadhurst says the upgrade of GA sadly doesn't fix this. Looks like we are [waiting for Google](https://code.google.com/p/analytics-issues/issues/detail?id=671) to address this.

As [suggested](https://forums.developer.apple.com/thread/8991) in the iOS devs forums, one needs to disable the bitcode option in the (generated cordova) xcode project. This should fix it. However, it is inconvenient for automated builds. The other option would be to just use xcode6 for now ;)

Also there's [some info](https://forums.developer.apple.com/message/23143#23143) that bitcode is only mandatory for watchOS apps, but this needs to be confirmed.

**Comment by cmackay** [comment] 2015-09-19 14:48
I just woke up and started looking into this more. I see you guys are way ahead of me :) I appreciate all the information. I am tracking the issue you linked @petarov and I will see if maybe I can disable the bitcode option through the plugin config. Not sure If that is possible but it might provide a good work around until an official fix is provided from Google. Let me know if either of you find any additional info and I will do the same. I am wondering if I might be able to use a similar approach from this article to have the plugin set the ENABLE_BITCODE = NO; option. http://ezosaleh.com/adjust-ios-deployment-target-with-cordova-hooks-nodejs  I will let you know what I find. Thanks!

**Comment by cmackay** [comment] 2015-09-19 15:35
http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

**Comment by cmackay** [comment] 2015-09-19 15:57
I guess there is not really much that can be done at this point until the native analytics sdk provides bit code. If anyone is having this issue, It looks like the best thing to do is to set ENABLE_BITCODE to NO as shown in the above stackoverflow post. It looks like watch apps require bitcode so hopefully there will be an SDK release soon so that the updates can integrated with this plugin.

**Comment by jensljungblad** [comment] 2015-09-24 19:01
I disabled bitcode but the plugin is not reporting to Analytics anymore :( Happened when building with the new Xcode.

**Comment by jensljungblad** [comment] 2015-09-24 19:58
I'm not good with Xcode or Obj-C but after placing a few breakpoints it seems it ends up in the `send` function:

```objc
  if (!tracker) {
    result = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"tracker not initialized"];
  } else {
    [tracker send:params];
    result = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
  }
```

And runs the `[tracker send:params];` line. Not sure what happens there. I can't seem to step inside that method, and I couldn't find it anywhere in the code.

**Comment by cmackay** [comment] 2015-09-24 22:47
tracker send is the native analytics tracker method

https://developers.google.com/analytics/devguides/collection/ios/v3/reference/protocol_g_a_i_tracker-p.html#ae200c9432a91242cf4e1e4917f353c14

**Comment by jensljungblad** [comment] 2015-09-25 05:38
So any idea why it's not working anymore? Is it working for anyone with the new Xcode?

**Comment by Deminetix** [comment] 2015-09-25 05:59
I just had XCode automatically update itself (i was specifically ignoring it as i don't want to worry about iOS9 yet) and came across this issue too.

I set bitcode to NO and now it builds and runs on a device fine. The other issue i had (and maybe the reason analytics aren't sending for you) is the introduction of transport security, which i fixed by adding NSAllowsArbitraryLoads=true in my plist file.

**Comment by jensljungblad** [comment] 2015-09-25 06:40
Tried that and also tried 
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
posted here: https://www.google.com/search?sclient=psy-ab&es_sm=91&btnG=Search&q=ns+allows+arbitrary+loads#q=google+analytics+app+transport+security+ios9

No luck. Still nothing being reported unfortunately.

**Comment by hussfelt** [comment] 2015-10-13 09:08
Just for reference:
https://code.google.com/p/analytics-issues/issues/detail?id=671

**Comment by cmackay** [comment] 2015-10-23 18:52
Looks like there is a new ios sdk with bitcode. I should have a new release of the plugin in the next day or so.

**Closed** 2015-10-23 22:27 UTC

**Comment by petarov** [comment] 2015-11-05 22:38
Pretty cool! Compiles flawlessly now :+1:
